title: "ExecutivePro"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2223S2-CS2103T-W09-4/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji

gems:
  - jekyll-toc
toc:
  min_level: 1
  max_level: 4

